site_name: NQSync Documentation
site_url: /documentation/

repo_url: https://github.com/BhumikaUpadhyay05/NQSync

theme:
  name: material
  logo: /docs/assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.tabs
    - toc.integrate
    - navigation.expand
    - navigation.instant

extra_css:
  - styles/extra.css

extra_javascript:
  - js/extra.js

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Contents:
      - Introduction: Contents/Introduction.md
      - Installation Guide: Contents/Installation-Guide.md
      - Getting started: Contents/Getting-Started.md
      - Understanding results: Contents/Undertanding-results.md
      - Developer Guide: Contents/Developer-guide.md
      - Future Works: Contents/Future-Works.md
